config/routes.rb
Rails.application.routes.draw do
  get "/pages/:page" => "pages#show"
  resources :users
  resources :sessions

  resources :posts do
    resources :comments
  end

  root 'pages#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :reply, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true, length: { maximum: 200 }
  validates :content, presence: true

end

app/models/posts.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true, length: { maximum: 200 }
  validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def logged_in?
    !!session[:user_id]
  end

  helper_method :logged_in?

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    find_comment
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  def edit
    find_comment
    find_post
  end

  def update
    find_post
    find_comment

    if @comment.update(comment_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    find_post
    find_comment

    @comment.destroy

    redirect_to @post
  end

  private
    def find_post
      @post = Post.find(params[:post_id])
    end

    def find_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      {reply: params[:comment][:reply], user: current_user, post: @post}
    end

end

app/controllers/concerns/posts_controller.rb
posts_controller.rb

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    find_post
  end

  def edit
    find_post
  end

  def update
    find_post

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    find_post

    @post.destroy

    redirect_to root_url
  end

  private
    def find_post
      @post = Post.find(params[:id])
    end

    def post_params
      {title: params[:post][:title], content: params[:post][:content], user: current_user}
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:sessions][:email])
    if @user && @user.authenticate(params[:sessions][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    find_user
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<p><strong><%= comment.reply %></strong></p>
<p>by <%= comment.user.username %></p>
<% if comment.user == current_user %>
  <%= link_to "Edit Comment", edit_post_comment_path(@post, comment) %>
  <%= link_to "Delete Comment", post_comment_path(@post, comment), :method => :delete %>
<% end %>

app/views/comments/_form.html.erb
<div class="container">
  <%= form_for([@post, @post.comments.build]) do |f| %>
    Reply: <%= f.text_field :reply %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<div class="container">
 <%= form_for([@post, @comment]) do |f| %>
   Reply: <%= f.text_field :reply %>
   <%= f.submit "Submit" %>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GLF</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
  </head>

  <body>
  <nav>
    <div class="nav-wrapper teal lighten-2">
      <ul id="nav-mobile" class="right hide-on-med-and-down">
       <% if logged_in? %>

        <li> <%= link_to "#{current_user.username}", user_path(current_user) %></li>
        <li> <%= link_to "Log Out", session_path(current_user), :method => :delete %></li>
        <li> <%= link_to 'New Post', new_post_path %></li>
       <% else %>

        <li> <%= link_to 'Register', new_user_path %></li>
        <li>   <%= link_to 'Login', new_session_path %></li>
      <% end %>
         <li> <%= link_to 'Home', root_url %></li>
        <li><a href="/posts">Message Board</a></li>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>


  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center black-text text-lighten-2" text-color:>The Gary Larson Foundation</h1>
        <div class="row center">
          <h5 class="header col s12 light">Together,we can make a difference in the lives of children with cancer.</h5>
        </div>
           <div class="parallax"><img src="https://scontent-yyz1-1.xx.fbcdn.net/v/t1.0-9/1185892_564430916948088_2052358177_n.jpg?oh=e20bb761d121d04463d9b8f10df6921b&oe=58CF858C"></div>
        <div class="row center">
          <a href="https://www.crowdrise.com/the-gary-larsen-foundation" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Donate here</a>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="" alt="trophy.jpg"></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <!-- <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2> -->
            <h5 class="center">HOW WE HELP</h5>

            <p class="light">The Gary Larsen Foundation was founded on passion, love, and the strength of friendship. Our profits go to aid children and their families in the fight against childhood cancer. Join us in our efforts to improve the lives of children everywhere. All of our proceeds go to Make a Wish Foundation, Ronald McDonald House, Happiness is Camping, and the Leukemia Lymphoma Society.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <!-- <h2 class="center brown-text"><i class="material-icons">group</i></h2> -->
            <h5 class="center">Story</h5>

            <p class="light">In 2001 Gary Larsen passed away from Leukemia. Gary Larsen was one of those people who had an infectious spirit. He was a best friend, a husband and a father who inspired everyone and anyone who crossed his path. And so, when he passed away, his closest friends and family could not let Gary's spirit go unremembered. </p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <!-- <h2 class="center brown-text"><i class="material-icons">settings</i></h2> -->
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

    </div>
  </div>

<div class="row center">
          <a href="/posts/index" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Join The Community</a>
        </div>

  <div class="carousel">
    <a class="carousel-item" href="#one!"><img src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/11751756_930421390349037_6266780466240447780_n.jpg?oh=c7e76adcaeda7f70b65541dee1fc31d8&oe=58C21661"></a>
    <a class="carousel-item" href="#two!"><img src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/11063815_930419793682530_6438227583097994270_n.jpg?oh=bce52f1e1aad8719cf7da029dfe7b00d&oe=58C0E85A"></a>
    <a class="carousel-item" href="#three!"><img src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/11745593_930420467015796_4215154589214215506_n.jpg?oh=79bd5ba96f7b488c60b3c7129ac7d464&oe=58BAEAE4"></a>
    <a class="carousel-item" href="#four!"><img src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/11214172_930422020348974_2934756831582741568_n.jpg?oh=3c05a210359ff3aa8efc5b016497262a&oe=58BEDD4F"></a>
    <a class="carousel-item" href="#five!"><img src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/11745935_930420250349151_4592093788822185177_n.jpg?oh=54c863c7e7ccc95fa676d20295ddad34&oe=58CFE3FF"></a>
  </div>

  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light"></h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="https://scontent-lga3-1.xx.fbcdn.net/t31.0-8/11054307_934108759980300_1316615962760554040_o.jpg" alt="2Trophy"></div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Contact Us</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a href="mailto:someone@yoursite.com">Email Us</a> </li>
           <li><a class="white-text" href="#!">Link 2</a></li>

          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="https://github.com/Kndekaru">Miles McArdle-Coe</a>
      </div>
    </div>
  </footer>


  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Edit your Post</h1>
  <%= form_for @post do |f| %>
    Title: <%= f.text_field :title %>
    Body: <%= f.text_field :content %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<h1 align="center">COMMUNITY BOARD</h1>
<div class="container">
  <ul>
    <% @posts.each do |post| %>
      <li><%= link_to "#{post.title}", post %> by <%= post.user.username %></li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>Create a Post</h1>
  <%= form_for @post do |f| %>
    Title: <%= f.text_field :title %>
    Body: <%= f.text_field :content %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>
</div>
<% if current_user == @post.user %>
  <%= link_to "Edit Post", edit_post_path %>
  <%= link_to "Delete Post", post_path(@post), :method => :delete %>
<% end %>
<h2 align="center">Comments:</h2>
<%= render @post.comments %>
<% if logged_in? %>
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <h1>Create an Account</h1>
  <%= form_for @user do |f| %>
    Username: <%= f.text_field :username %>
    Email: <%= f.text_field :email %>
    Password: <%= f.password_field :password %>
    Confirm Password: <%= f.password_field :password_confirmation %>
    <%= f.submit "Sign Up" %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= "#{@user.username}'s Profile" %></h1>